// SPDX-License-Identifier: Apache-2.0

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Unity.RerunSDK.Core;

namespace Unity.RerunSDK.Editor
{
    public static class RerunSourceEmitter
    {
        public enum LogKind
        {
            TextLog,
            Scalar,
            Transform3D,
        }

        public enum MemberKind
        {
            Field,
            Property,
            ThisTransform,
        }

        public sealed class LogEntry
        {
            public LogEntry(
                LogKind kind,
                MemberKind memberKind,
                string memberName,
                string typeName,
                string entityPath,
                float rateHz,
                string level)
            {
                Kind = kind;
                MemberKind = memberKind;
                MemberName = memberName;
                TypeName = typeName;
                EntityPath = entityPath;
                RateHz = rateHz;
                Level = string.IsNullOrEmpty(level) ? "INFO" : level;
            }

            public LogKind Kind { get; }
            public MemberKind MemberKind { get; }
            public string MemberName { get; }
            public string TypeName { get; }
            public string EntityPath { get; }
            public float RateHz { get; }
            public string Level { get; }
        }

        public static string EmitClass(
            string ns,
            string className,
            IReadOnlyList<LogEntry> entries,
            string accessibility = "public",
            bool wrapForPlayerFallback = false)
        {
            if (string.IsNullOrWhiteSpace(className))
                throw new ArgumentException("Class name is required.", nameof(className));
            if (entries == null || entries.Count == 0)
                throw new ArgumentException("At least one generated log entry is required.", nameof(entries));

            for (int i = 0; i < entries.Count; i++)
                ValidateEntry(entries[i]);

            var pad = string.IsNullOrEmpty(ns) ? "" : "    ";
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            if (wrapForPlayerFallback)
            {
                sb.AppendLine("// Generated as a physical fallback for Player/IL2CPP builds.");
                sb.AppendLine("#if !UNITY_EDITOR");
            }

            sb.AppendLine("using System;");
            sb.AppendLine("using System.Globalization;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Scripting;");
            sb.AppendLine("using Unity.RerunSDK.Unity;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"{pad}[Preserve]");
            sb.AppendLine($"{pad}{NormalizeAccessibility(accessibility)} partial class {className} : IRerunGeneratedLogSource");
            sb.AppendLine($"{pad}{{");
            sb.AppendLine($"{pad}    public int RerunLog_EntryCount => {entries.Count.ToString(CultureInfo.InvariantCulture)};");
            sb.AppendLine();
            EmitEntryMetadata(entries, sb, pad);
            EmitPublish(entries, sb, pad);
            sb.AppendLine($"{pad}}}");

            if (!string.IsNullOrEmpty(ns))
                sb.AppendLine("}");
            if (wrapForPlayerFallback)
                sb.AppendLine("#endif");

            return sb.ToString();
        }

        private static void EmitEntryMetadata(IReadOnlyList<LogEntry> entries, StringBuilder sb, string pad)
        {
            sb.AppendLine($"{pad}    public RerunGeneratedLogEntry RerunLog_GetEntry(int index)");
            sb.AppendLine($"{pad}    {{");
            sb.AppendLine($"{pad}        switch (index)");
            sb.AppendLine($"{pad}        {{");
            for (int i = 0; i < entries.Count; i++)
            {
                var e = entries[i];
                sb.AppendLine($"{pad}            case {i}: return new RerunGeneratedLogEntry(\"{Escape(e.EntityPath)}\", RerunGeneratedLogKind.{ToRuntimeKind(e.Kind)}, {FormatFloat(e.RateHz)}f, \"{Escape(e.Level)}\");");
            }
            sb.AppendLine($"{pad}            default: throw new ArgumentOutOfRangeException(nameof(index));");
            sb.AppendLine($"{pad}        }}");
            sb.AppendLine($"{pad}    }}");
            sb.AppendLine();
        }

        private static void EmitPublish(IReadOnlyList<LogEntry> entries, StringBuilder sb, string pad)
        {
            sb.AppendLine($"{pad}    public void RerunLog_Publish(int index, RerunManager manager)");
            sb.AppendLine($"{pad}    {{");
            sb.AppendLine($"{pad}        if (manager == null) return;");
            sb.AppendLine($"{pad}        switch (index)");
            sb.AppendLine($"{pad}        {{");
            for (int i = 0; i < entries.Count; i++)
            {
                sb.AppendLine($"{pad}            case {i}:");
                sb.AppendLine($"{pad}                {EmitPublishStatement(entries[i])}");
                sb.AppendLine($"{pad}                break;");
            }
            sb.AppendLine($"{pad}            default: throw new ArgumentOutOfRangeException(nameof(index));");
            sb.AppendLine($"{pad}        }}");
            sb.AppendLine($"{pad}    }}");
        }

        private static string EmitPublishStatement(LogEntry e)
        {
            var path = Escape(e.EntityPath);
            switch (e.Kind)
            {
                case LogKind.TextLog:
                    return $"manager.LogText(\"{path}\", this.{e.MemberName}, \"{Escape(e.Level)}\");";
                case LogKind.Scalar:
                    return $"manager.LogScalar(\"{path}\", Convert.ToDouble(this.{e.MemberName}, CultureInfo.InvariantCulture));";
                case LogKind.Transform3D:
                    if (e.MemberKind == MemberKind.ThisTransform)
                        return $"manager.LogTransform(\"{path}\", this.transform);";
                    if (IsGameObjectType(e.TypeName))
                        return $"if (this.{e.MemberName} != null) manager.LogTransform(\"{path}\", this.{e.MemberName}.transform);";
                    return $"if (this.{e.MemberName} != null) manager.LogTransform(\"{path}\", this.{e.MemberName});";
                default:
                    throw new ArgumentOutOfRangeException(nameof(e.Kind));
            }
        }

        private static void ValidateEntry(LogEntry entry)
        {
            if (entry == null)
                throw new ArgumentNullException(nameof(entry));
            if (string.IsNullOrWhiteSpace(entry.EntityPath))
                throw new ArgumentException("Entity path is required.", nameof(entry));
            RerunEntityPath.FromString(entry.EntityPath);
            if (entry.Kind != LogKind.Transform3D && string.IsNullOrWhiteSpace(entry.MemberName))
                throw new ArgumentException("Member name is required.", nameof(entry));
        }

        private static bool IsGameObjectType(string typeName)
            => string.Equals(typeName, "UnityEngine.GameObject", StringComparison.Ordinal)
               || string.Equals(typeName, "GameObject", StringComparison.Ordinal);

        private static string ToRuntimeKind(LogKind kind)
            => kind == LogKind.TextLog ? "TextLog" :
               kind == LogKind.Scalar ? "Scalar" :
               "Transform3D";

        private static string NormalizeAccessibility(string accessibility)
        {
            return string.IsNullOrWhiteSpace(accessibility) ? "public" : accessibility.Trim();
        }

        private static string FormatFloat(float value)
            => value.ToString("0.0########", CultureInfo.InvariantCulture);

        private static string Escape(string value)
            => (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
