// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rerun/v1alpha1/sdk_comms.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Rerun.SdkComms.V1Alpha1 {
  /// <summary>
  /// Simple buffer for messages between SDKs and viewers.
  ///
  /// - SDKs produce messages by calling `WriteMessages`
  /// - Viewers consume messages by calling `ReadMessages`
  ///
  /// The buffer is bounded by a memory limit, and will drop the oldest messages when the limit is reached.
  ///
  /// Whenever `ReadMessages` is called, all buffered messages are sent in the order they were received.
  /// The stream will then also yield any new messages passed to `WriteMessages` from any client.
  /// </summary>
  public static partial class MessageProxyService
  {
    static readonly string __ServiceName = "rerun.sdk_comms.v1alpha1.MessageProxyService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Rerun.SdkComms.V1Alpha1.WriteMessagesRequest> __Marshaller_rerun_sdk_comms_v1alpha1_WriteMessagesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Rerun.SdkComms.V1Alpha1.WriteMessagesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Rerun.SdkComms.V1Alpha1.WriteMessagesResponse> __Marshaller_rerun_sdk_comms_v1alpha1_WriteMessagesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Rerun.SdkComms.V1Alpha1.WriteMessagesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Rerun.SdkComms.V1Alpha1.ReadMessagesRequest> __Marshaller_rerun_sdk_comms_v1alpha1_ReadMessagesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Rerun.SdkComms.V1Alpha1.ReadMessagesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Rerun.SdkComms.V1Alpha1.ReadMessagesResponse> __Marshaller_rerun_sdk_comms_v1alpha1_ReadMessagesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Rerun.SdkComms.V1Alpha1.ReadMessagesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Rerun.SdkComms.V1Alpha1.WriteTableRequest> __Marshaller_rerun_sdk_comms_v1alpha1_WriteTableRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Rerun.SdkComms.V1Alpha1.WriteTableRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Rerun.SdkComms.V1Alpha1.WriteTableResponse> __Marshaller_rerun_sdk_comms_v1alpha1_WriteTableResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Rerun.SdkComms.V1Alpha1.WriteTableResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Rerun.SdkComms.V1Alpha1.ReadTablesRequest> __Marshaller_rerun_sdk_comms_v1alpha1_ReadTablesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Rerun.SdkComms.V1Alpha1.ReadTablesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Rerun.SdkComms.V1Alpha1.ReadTablesResponse> __Marshaller_rerun_sdk_comms_v1alpha1_ReadTablesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Rerun.SdkComms.V1Alpha1.ReadTablesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Rerun.SdkComms.V1Alpha1.SaveScreenshotRequest> __Marshaller_rerun_sdk_comms_v1alpha1_SaveScreenshotRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Rerun.SdkComms.V1Alpha1.SaveScreenshotRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Rerun.SdkComms.V1Alpha1.SaveScreenshotResponse> __Marshaller_rerun_sdk_comms_v1alpha1_SaveScreenshotResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Rerun.SdkComms.V1Alpha1.SaveScreenshotResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Rerun.SdkComms.V1Alpha1.WriteMessagesRequest, global::Rerun.SdkComms.V1Alpha1.WriteMessagesResponse> __Method_WriteMessages = new grpc::Method<global::Rerun.SdkComms.V1Alpha1.WriteMessagesRequest, global::Rerun.SdkComms.V1Alpha1.WriteMessagesResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "WriteMessages",
        __Marshaller_rerun_sdk_comms_v1alpha1_WriteMessagesRequest,
        __Marshaller_rerun_sdk_comms_v1alpha1_WriteMessagesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Rerun.SdkComms.V1Alpha1.ReadMessagesRequest, global::Rerun.SdkComms.V1Alpha1.ReadMessagesResponse> __Method_ReadMessages = new grpc::Method<global::Rerun.SdkComms.V1Alpha1.ReadMessagesRequest, global::Rerun.SdkComms.V1Alpha1.ReadMessagesResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ReadMessages",
        __Marshaller_rerun_sdk_comms_v1alpha1_ReadMessagesRequest,
        __Marshaller_rerun_sdk_comms_v1alpha1_ReadMessagesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Rerun.SdkComms.V1Alpha1.WriteTableRequest, global::Rerun.SdkComms.V1Alpha1.WriteTableResponse> __Method_WriteTable = new grpc::Method<global::Rerun.SdkComms.V1Alpha1.WriteTableRequest, global::Rerun.SdkComms.V1Alpha1.WriteTableResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "WriteTable",
        __Marshaller_rerun_sdk_comms_v1alpha1_WriteTableRequest,
        __Marshaller_rerun_sdk_comms_v1alpha1_WriteTableResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Rerun.SdkComms.V1Alpha1.ReadTablesRequest, global::Rerun.SdkComms.V1Alpha1.ReadTablesResponse> __Method_ReadTables = new grpc::Method<global::Rerun.SdkComms.V1Alpha1.ReadTablesRequest, global::Rerun.SdkComms.V1Alpha1.ReadTablesResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ReadTables",
        __Marshaller_rerun_sdk_comms_v1alpha1_ReadTablesRequest,
        __Marshaller_rerun_sdk_comms_v1alpha1_ReadTablesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Rerun.SdkComms.V1Alpha1.SaveScreenshotRequest, global::Rerun.SdkComms.V1Alpha1.SaveScreenshotResponse> __Method_SaveScreenshot = new grpc::Method<global::Rerun.SdkComms.V1Alpha1.SaveScreenshotRequest, global::Rerun.SdkComms.V1Alpha1.SaveScreenshotResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveScreenshot",
        __Marshaller_rerun_sdk_comms_v1alpha1_SaveScreenshotRequest,
        __Marshaller_rerun_sdk_comms_v1alpha1_SaveScreenshotResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Rerun.SdkComms.V1Alpha1.SdkCommsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for MessageProxyService</summary>
    public partial class MessageProxyServiceClient : grpc::ClientBase<MessageProxyServiceClient>
    {
      /// <summary>Creates a new client for MessageProxyService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MessageProxyServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MessageProxyService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MessageProxyServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MessageProxyServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MessageProxyServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// TODO(jan): Would it be more efficient to send a "message batch" instead of individual messages?
      ///            It may allow us to amortize the overhead of the gRPC protocol.
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::Rerun.SdkComms.V1Alpha1.WriteMessagesRequest, global::Rerun.SdkComms.V1Alpha1.WriteMessagesResponse> WriteMessages(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return WriteMessages(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// TODO(jan): Would it be more efficient to send a "message batch" instead of individual messages?
      ///            It may allow us to amortize the overhead of the gRPC protocol.
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::Rerun.SdkComms.V1Alpha1.WriteMessagesRequest, global::Rerun.SdkComms.V1Alpha1.WriteMessagesResponse> WriteMessages(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_WriteMessages, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Rerun.SdkComms.V1Alpha1.ReadMessagesResponse> ReadMessages(global::Rerun.SdkComms.V1Alpha1.ReadMessagesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadMessages(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Rerun.SdkComms.V1Alpha1.ReadMessagesResponse> ReadMessages(global::Rerun.SdkComms.V1Alpha1.ReadMessagesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ReadMessages, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Rerun.SdkComms.V1Alpha1.WriteTableResponse WriteTable(global::Rerun.SdkComms.V1Alpha1.WriteTableRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return WriteTable(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Rerun.SdkComms.V1Alpha1.WriteTableResponse WriteTable(global::Rerun.SdkComms.V1Alpha1.WriteTableRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_WriteTable, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Rerun.SdkComms.V1Alpha1.WriteTableResponse> WriteTableAsync(global::Rerun.SdkComms.V1Alpha1.WriteTableRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return WriteTableAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Rerun.SdkComms.V1Alpha1.WriteTableResponse> WriteTableAsync(global::Rerun.SdkComms.V1Alpha1.WriteTableRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_WriteTable, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Rerun.SdkComms.V1Alpha1.ReadTablesResponse> ReadTables(global::Rerun.SdkComms.V1Alpha1.ReadTablesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadTables(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Rerun.SdkComms.V1Alpha1.ReadTablesResponse> ReadTables(global::Rerun.SdkComms.V1Alpha1.ReadTablesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ReadTables, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Rerun.SdkComms.V1Alpha1.SaveScreenshotResponse SaveScreenshot(global::Rerun.SdkComms.V1Alpha1.SaveScreenshotRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveScreenshot(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Rerun.SdkComms.V1Alpha1.SaveScreenshotResponse SaveScreenshot(global::Rerun.SdkComms.V1Alpha1.SaveScreenshotRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveScreenshot, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Rerun.SdkComms.V1Alpha1.SaveScreenshotResponse> SaveScreenshotAsync(global::Rerun.SdkComms.V1Alpha1.SaveScreenshotRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveScreenshotAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Rerun.SdkComms.V1Alpha1.SaveScreenshotResponse> SaveScreenshotAsync(global::Rerun.SdkComms.V1Alpha1.SaveScreenshotRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveScreenshot, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MessageProxyServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MessageProxyServiceClient(configuration);
      }
    }

  }
}
#endregion
