// Copyright (c) 2026 Jianbin Liu and Unity2Rerun contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor
// Purpose: Provides Unity Editor Inspector and build-time tooling for Unity2Rerun.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Unity.RerunSDK.Unity;
using UnityEngine;

namespace Unity.RerunSDK.Editor
{
    /// <summary>
    /// Provides Unity Editor support for Rerun Log Code Generator.
    /// </summary>
    public static class RerunLogCodeGenerator
    {
        private const string OutputDir = "Assets/Scripts/Generated/RerunLog";
        /// <summary>
        /// Handles the GenerateSourceFiles workflow for this component.
        /// </summary>
        public static List<string> GenerateSourceFiles()
        {
            var byType = CollectRerunLogTypes();
            return GenerateSourceFiles(byType, out _);
        }
        /// <summary>
        /// Handles the GenerateSourceFiles workflow for this component.
        /// </summary>
        public static List<string> GenerateSourceFiles(
            Dictionary<Type, List<RerunSourceEmitter.LogEntry>> byType,
            out bool wroteAnyFiles)
        {
            wroteAnyFiles = false;
            var generatedFiles = new List<string>();
            var absoluteOutputDir = Path.Combine(Application.dataPath, "Scripts/Generated/RerunLog");

            if (byType.Count == 0)
            {
                wroteAnyFiles = DeleteStaleGeneratedFiles(absoluteOutputDir, generatedFiles);
                return generatedFiles;
            }

            Directory.CreateDirectory(absoluteOutputDir);
            foreach (var kv in byType)
            {
                var source = RerunSourceEmitter.EmitClass(
                    kv.Key.Namespace ?? "",
                    kv.Key.Name,
                    kv.Value,
                    GetAccessibility(kv.Key),
                    wrapForPlayerFallback: true);
                var fileName = Sanitize(kv.Key.FullName ?? kv.Key.Name) + "_RerunLog.g.cs";
                var absolutePath = Path.Combine(absoluteOutputDir, fileName);

                if (!File.Exists(absolutePath) || File.ReadAllText(absolutePath) != source)
                {
                    File.WriteAllText(absolutePath, source, System.Text.Encoding.UTF8);
                    wroteAnyFiles = true;
                }

                generatedFiles.Add(absolutePath);
            }

            wroteAnyFiles |= DeleteStaleGeneratedFiles(absoluteOutputDir, generatedFiles);
            return generatedFiles;
        }

        public static Dictionary<Type, List<RerunSourceEmitter.LogEntry>> CollectRerunLogTypes()
        {
            var result = new Dictionary<Type, List<RerunSourceEmitter.LogEntry>>();
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try
                {
                    types = asm.GetTypes();
                }
                catch (ReflectionTypeLoadException ex)
                {
                    types = ex.Types.Where(t => t != null).ToArray();
                }

                foreach (var type in types)
                {
                    if (type == null || !type.IsClass)
                        continue;
                    if (!typeof(MonoBehaviour).IsAssignableFrom(type))
                        continue;

                    var entries = ScanType(type);
                    if (entries.Count > 0)
                        result[type] = entries;
                }
            }

            return result;
        }
        /// <summary>
        /// Handles the EmitLinkXml workflow for this component.
        /// </summary>
        public static string EmitLinkXml(IEnumerable<Type> types)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            sb.AppendLine("<!-- Generated by RerunLogBuildPreprocess; do not edit by hand. -->");
            sb.AppendLine("<linker>");
            var seen = new HashSet<string>();
            foreach (var type in types.OrderBy(t => t.Assembly.GetName().Name).ThenBy(t => t.FullName))
            {
                var assemblyName = type.Assembly.GetName().Name;
                var fullName = type.FullName ?? type.Name;
                if (!seen.Add(assemblyName + ":" + fullName))
                    continue;
                sb.AppendLine($"  <assembly fullname=\"{EscapeXml(assemblyName)}\">");
                sb.AppendLine($"    <type fullname=\"{EscapeXml(fullName)}\" preserve=\"all\" />");
                sb.AppendLine("  </assembly>");
            }
            sb.AppendLine("</linker>");
            return sb.ToString();
        }

        public static string OutputDirectory => OutputDir;

        private static List<RerunSourceEmitter.LogEntry> ScanType(Type type)
        {
            var entries = new List<RerunSourceEmitter.LogEntry>();
            var classTransform = type.GetCustomAttribute<RerunTransformAttribute>();
            if (classTransform != null)
            {
                entries.Add(new RerunSourceEmitter.LogEntry(
                    RerunSourceEmitter.LogKind.Transform3D,
                    RerunSourceEmitter.MemberKind.ThisTransform,
                    "this",
                    typeof(Transform).FullName,
                    classTransform.EntityPath,
                    classTransform.RateHz,
                    "INFO"));
            }

            const BindingFlags flags = BindingFlags.Instance | BindingFlags.Public |
                                       BindingFlags.NonPublic | BindingFlags.DeclaredOnly;
            foreach (var field in type.GetFields(flags))
                AddFieldEntries(entries, field);
            foreach (var property in type.GetProperties(flags))
                AddPropertyEntries(entries, property);

            return entries;
        }

        private static void AddFieldEntries(List<RerunSourceEmitter.LogEntry> entries, FieldInfo field)
        {
            foreach (var attr in field.GetCustomAttributes<RerunLogAttribute>())
            {
                EnsureTextLogType(field.FieldType, field.Name);
                entries.Add(CreateEntry(RerunSourceEmitter.LogKind.TextLog,
                    RerunSourceEmitter.MemberKind.Field, field.Name, field.FieldType, attr.EntityPath, attr.RateHz, attr.Level));
            }

            foreach (var attr in field.GetCustomAttributes<RerunScalarAttribute>())
            {
                EnsureScalarType(field.FieldType, field.Name);
                entries.Add(CreateEntry(RerunSourceEmitter.LogKind.Scalar,
                    RerunSourceEmitter.MemberKind.Field, field.Name, field.FieldType, attr.EntityPath, attr.RateHz, "INFO"));
            }

            foreach (var attr in field.GetCustomAttributes<RerunTransformAttribute>())
            {
                EnsureTransformType(field.FieldType, field.Name);
                entries.Add(CreateEntry(RerunSourceEmitter.LogKind.Transform3D,
                    RerunSourceEmitter.MemberKind.Field, field.Name, field.FieldType, attr.EntityPath, attr.RateHz, "INFO"));
            }
        }

        private static void AddPropertyEntries(List<RerunSourceEmitter.LogEntry> entries, PropertyInfo property)
        {
            if (property.GetMethod == null)
                return;

            foreach (var attr in property.GetCustomAttributes<RerunLogAttribute>())
            {
                EnsureTextLogType(property.PropertyType, property.Name);
                entries.Add(CreateEntry(RerunSourceEmitter.LogKind.TextLog,
                    RerunSourceEmitter.MemberKind.Property, property.Name, property.PropertyType, attr.EntityPath, attr.RateHz, attr.Level));
            }

            foreach (var attr in property.GetCustomAttributes<RerunScalarAttribute>())
            {
                EnsureScalarType(property.PropertyType, property.Name);
                entries.Add(CreateEntry(RerunSourceEmitter.LogKind.Scalar,
                    RerunSourceEmitter.MemberKind.Property, property.Name, property.PropertyType, attr.EntityPath, attr.RateHz, "INFO"));
            }

            foreach (var attr in property.GetCustomAttributes<RerunTransformAttribute>())
            {
                EnsureTransformType(property.PropertyType, property.Name);
                entries.Add(CreateEntry(RerunSourceEmitter.LogKind.Transform3D,
                    RerunSourceEmitter.MemberKind.Property, property.Name, property.PropertyType, attr.EntityPath, attr.RateHz, "INFO"));
            }
        }

        private static RerunSourceEmitter.LogEntry CreateEntry(
            RerunSourceEmitter.LogKind kind,
            RerunSourceEmitter.MemberKind memberKind,
            string memberName,
            Type type,
            string entityPath,
            float rateHz,
            string level)
        {
            return new RerunSourceEmitter.LogEntry(
                kind, memberKind, memberName, type.FullName ?? type.Name, entityPath, rateHz, level);
        }

        private static void EnsureTextLogType(Type type, string memberName)
        {
            if (type != typeof(string))
                throw new InvalidOperationException($"[RerunLog] member '{memberName}' must be string.");
        }

        private static void EnsureScalarType(Type type, string memberName)
        {
            if (type == typeof(float) || type == typeof(double) ||
                type == typeof(byte) || type == typeof(sbyte) ||
                type == typeof(short) || type == typeof(ushort) ||
                type == typeof(int) || type == typeof(uint) ||
                type == typeof(long) || type == typeof(ulong))
                return;
            throw new InvalidOperationException($"[RerunScalar] member '{memberName}' must be numeric.");
        }

        private static void EnsureTransformType(Type type, string memberName)
        {
            if (typeof(Transform).IsAssignableFrom(type) || typeof(GameObject).IsAssignableFrom(type))
                return;
            throw new InvalidOperationException($"[RerunTransform] member '{memberName}' must be Transform or GameObject.");
        }

        private static bool DeleteStaleGeneratedFiles(string absoluteOutputDir, IReadOnlyCollection<string> generatedFiles)
        {
            if (!Directory.Exists(absoluteOutputDir))
                return false;

            var deletedAny = false;
            var keep = new HashSet<string>(generatedFiles, StringComparer.OrdinalIgnoreCase);
            foreach (var path in Directory.GetFiles(absoluteOutputDir, "*_RerunLog.g.cs"))
            {
                if (keep.Contains(path))
                    continue;
                File.Delete(path);
                deletedAny = true;
                var meta = path + ".meta";
                if (File.Exists(meta))
                {
                    File.Delete(meta);
                    deletedAny = true;
                }
            }

            return deletedAny;
        }

        private static string GetAccessibility(Type type)
            => type.IsPublic || type.IsNestedPublic ? "public" : "internal";

        private static string Sanitize(string value)
        {
            var chars = value.ToCharArray();
            for (var i = 0; i < chars.Length; i++)
            {
                if (!char.IsLetterOrDigit(chars[i]))
                    chars[i] = '_';
            }
            return new string(chars);
        }

        private static string EscapeXml(string value)
            => value.Replace("&", "&amp;").Replace("\"", "&quot;")
                .Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
